stages:
  - build
  - test
  - deploy

build-locally:
  stage: build
  image: "node:19-alpine"
  script:
    - npm i
    - set -e
    - npm run dev > >(tee -a output.log) 2>&1 &
    - sleep 5
    - kill -INT $! || true
    - echo "Stopping the program if necessary"
    - if grep -q "error" output.log; then exit 1; fi

lint-test-job:
  stage: test
  image: "node:19-alpine"
  script:
    - npm i
    - npm i prettier
    - echo "Linting code..."
    # - npx prettier --write src
    # - npx prettier --check src
    # - npx eslint src --fix

unit-test-job:
  stage: test
  image: "node:19-alpine"
  script:
    - npm i
    # - npm run test:unit 				# Tests later when there is actually something to test
    - sleep 3
    - echo "Guess it works"

deploy-dev-job:
  stage: deploy
  script:
    - docker stop ppl-frontend-dev || true
    - docker rm ppl-frontend-dev || true
    # - cp $DOT_ENV_DEV .env
    - docker build -f Dockerfile -t ppl-frontend-dev-img .
    - docker run -d -p 5173:5173 --name ppl-frontend-dev ppl-frontend-dev-img
  only:
    - development
